-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 08:47:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storedb` DEFAULT CHARACTER SET utf8 ;
USE `storedb` ;

-- -----------------------------------------------------
-- Table `storedb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storedb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `description` VARCHAR(300) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storedb`.`User_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storedb`.`User_has_Product` (
  `User_idUser` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Product_idProduct`),
  INDEX `fk_User_has_Product_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  INDEX `fk_User_has_Product_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Product_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `storedb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Product_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `storedb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
